apiVersion: v1
kind: PersistentVolume
metadata:
  name: vchat-mysql-pvc
spec:
  storageClassName: mysql-record
#  容量
  capacity:
    storage: 1Gi
#    连接方式
  accessModes:
    - ReadWriteOnce
#  挂载地址
  hostPath:
    path: "/mnt/data"